spring:
  session:
    store-type: jdbc
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa/h2/bin/shop_test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
